<a href="https://colab.research.google.com/github/RandraFerdian/Numpy_guide/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Installasi & Import

####Installasi

In [3]:
pip install numpy

####Import

In [4]:
import numpy as np

#Membuat Array

####**Dari List Python: np.array()**

In [8]:
# Membuat array 1 dimensi (vektor)
list_saya = [1, 2, 3, 4, 5]
arr_1d = np.array(list_saya)

print("array 1 Dimensi")
print(arr_1d)
# Output: [1 2 3 4 5]

# Membuat array 2 dimensi (matriks) dari list bersarang
list_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(list_2d)

print("array 2 Dimensi")
print(arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Membuat array 3 dimensi (matriks) dari list
list_3d = [[1, 2, 3], [4, 5, 6],[7,8,9]]
arr_3d = np.array(list_3d)

print("array 3 Dimensi")
print(arr_3d)

array 1 Dimensi
[1 2 3 4 5]
array 2 Dimensi
[[1 2 3]
 [4 5 6]]
array 3 Dimensi
[[1 2 3]
 [4 5 6]
 [7 8 9]]


####**Menggunakan Fungsi Bawaan NumPy**




#####np.arange(start, stop, step)

Membuat array dengan nilai dalam rentang tertentu, mirip seperti range() pada Python.

In [7]:
arr_range = np.arange(0, 10, 2) # Mulai dari 0, berhenti sebelum 10, dengan langkah 2
print(arr_range)
# Output: [0 2 4 6 8]

[0 2 4 6 8]


#####np.zeros(shape)

Membuat array yang semua elemennya berisi angka 0.

In [ ]:
arr_zeros = np.zeros((2, 3)) # Membuat matriks 2x3 berisi nol
print(arr_zeros)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

#####np.ones(shape)

Sama seperti np.zeros(), tetapi semua elemennya berisi angka 1.

In [9]:
arr_ones = np.ones((3, 2)) # Membuat matriks 3x2 berisi satu
print(arr_ones)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#####np.linspace(start, stop, num)

Membuat array dengan sejumlah num elemen yang terdistribusi secara merata antara start dan stop.

In [15]:
arr_space = np.linspace(0, 1, 5) # 5 angka dari 0 hingga 1 (inklusif)
print(arr_space)
# Output: [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


#####np.random.rand(d0, d1, ...)

Membuat array dengan bentuk tertentu yang diisi dengan angka acak dari distribusi uniform (antara 0 dan 1).

In [25]:
arr_rand = np.random.rand(2, 3) # Matriks acak 2x3
print(arr_rand)
# Output akan bervariasi, contoh:
# [[0.123 0.456 0.789]
#  [0.987 0.654 0.321]]

[[0.37825412 0.51729824 0.2840102 ]
 [0.67101233 0.87475129 0.37286085]]


#Atribut Penting ndarray

Setiap ndarray memiliki atribut yang mendeskripsikan propertinya.

In [26]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# .shape: Mengetahui dimensi (bentuk) array
print(arr_2d.shape) # Output: (2, 3) -> 2 baris, 3 kolom

# .ndim: Mengetahui jumlah dimensi
print(arr_2d.ndim) # Output: 2

# .size: Mengetahui jumlah total elemen
print(arr_2d.size) # Output: 6

# .dtype: Mengetahui tipe data elemen di dalam array
print(arr_2d.dtype) # Output: int64 (tergantung sistem operasi)

(2, 3)
2
6
int64


#Indexing dan Slicing (Mengakses Elemen)

Ini adalah cara untuk mengambil elemen atau sekelompok elemen dari sebuah array.

####Array 1D

In [ ]:
arr_1d = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]

# Mengambil elemen di indeks ke-2
print(arr_1d[2]) # Output: 2

# Mengambil elemen dari indeks 2 hingga 5 (indeks 5 tidak termasuk)
print(arr_1d[2:5]) # Output: [2 3 4]

####Array 2D (Matriks)

In [30]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Mengambil satu elemen (baris 1, kolom 2)
print(arr_2d[1, 2]) # Output: 6

# Mengambil satu baris utuh (baris ke-0)
print(arr_2d[0, :]) # Output: [1 2 3]
# atau lebih singkat
print(arr_2d[0])

# Mengambil satu kolom utuh (kolom ke-1)
print(arr_2d[:, 1]) # Output: [2 5 8]

# Slicing sub-matriks (baris 0-1, kolom 1-2)
print(arr_2d[0:2, 1:3])
# Output:
# [[2 3]
#  [5 6]]

6
[1 2 3]
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


####Boolean Indexing (Filtering)

In [32]:
arr = np.arange(1, 11) # [ 1  2  3  4  5  6  7  8  9 10]

# Buat kondisi
kondisi = arr > 5
print(kondisi) # Output: [False False False False False  True  True  True  True  True]

# Gunakan kondisi untuk memfilter array
print(arr[kondisi]) # Output: [ 6  7  8  9 10]

# Bisa juga digabungkan dalam satu baris
print(arr[arr % 2 == 0]) # Mengambil semua elemen genap -> [ 2  4  6  8 10]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 2  4  6  8 10]


#Operasi Matematika

####Operasi Element-wise

Operasi aritmatika pada array dilakukan per elemen (element-wise).

In [33]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Penjumlahan
print(arr_a + arr_b) # Output: [5 7 9]

# Perkalian
print(arr_a * arr_b) # Output: [ 4 10 18]

# Operasi dengan skalar (satu angka)
print(arr_a * 2) # Output: [2 4 6]

[5 7 9]
[ 4 10 18]
[2 4 6]


####Universal Functions (Ufuncs)

NumPy menyediakan fungsi matematika yang bisa beroperasi pada seluruh elemen array secara efisien.

In [35]:
arr = np.array([1, 4, 9])

# Akar kuadrat
print(np.sqrt(arr)) # Output: [1. 2. 3.]

# Eksponensial
print(np.exp(arr)) #Output: [2.71828183e+00 5.45981500e+01 8.10308393e+03]

# Sinus
print(np.sin(arr)) #Output: [ 0.84147098 -0.7568025   0.41211849]

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[ 0.84147098 -0.7568025   0.41211849]


####Operasi Agregasi (Statistika)

Menghitung nilai tunggal dari sebuah array.
axis=0: Operasi dilakukan secara vertikal (sepanjang kolom).


*   axis=1: Operasi dilakukan secara horizontal (sepanjang baris).
*   axis=0: Operasi dilakukan secara vertikal (sepanjang kolom).

In [42]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Menjumlahkan semua elemen
print(arr_2d.sum()) # Output: 21

# Menghitung rata-rata
print(arr_2d.mean()) # Output: 3.5

#Menghitung Max
print(arr_2d.max())

#Menghitung Min
print(arr_2d.min())

# Menjumlahkan per kolom (axis=0)
print(arr_2d.sum(axis=0)) # Output: [5 7 9] -> (1+4, 2+5, 3+6)

# Menjumlahkan per baris (axis=1)
print(arr_2d.sum(axis=1)) # Output: [ 6 15] -> (1+2+3, 4+5+6)

21
3.5
6
1
[5 7 9]
[ 6 15]


#Manipulasi Bentuk Array

####Merubah Bentuk: reshape()

Fungsi ini mengubah array ke bentuk baru. Syaratnya, jumlah elemen total harus tetap sama.

In [43]:
# Array 1D dengan 12 elemen
arr_1d = np.arange(12)
print("Original:", arr_1d)
# Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

# Diubah menjadi matriks 3 baris 4 kolom (3 * 4 = 12 elemen)
arr_3x4 = arr_1d.reshape(3, 4)
print("\nReshaped 3x4:\n", arr_3x4)
# Reshaped 3x4:
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#Menggabungkan dan Memecah Array

####Menggabungkan Array: np.concatenate, np.vstack, np.hstack

In [44]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Menumpuk baris (vertical)
v_stack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", v_stack)
# Vertical Stack:
#  [[1 2]
#   [3 4]
#   [5 6]
#   [7 8]]
# Bentuknya menjadi (4, 2)

# Menjajarkan kolom (horizontal)
h_stack = np.hstack((arr1, arr2))
print("\nHorizontal Stack:\n", h_stack)
# Horizontal Stack:
#  [[1 2 5 6]
#   [3 4 7 8]]
# Bentuknya menjadi (2, 4)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


#Broadcasting

Broadcasting adalah salah satu fitur paling kuat di NumPy. Ini adalah mekanisme yang memungkinkan NumPy melakukan operasi matematika pada array dengan bentuk (shape) yang berbeda.

Secara sederhana, jika salah satu array lebih kecil, NumPy akan "menyebarkan" atau "memperluas" array yang lebih kecil tersebut agar bentuknya cocok untuk operasi.

In [45]:
#contoh 1
arr = np.array([1, 2, 3])
hasil = arr + 5 # Sebenarnya, 5 di-broadcast menjadi [5, 5, 5]
print(hasil)
# Output: [6 7 8]


#Contoh 2
# Matriks 3x3
matriks = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Vektor 1x3
vektor = np.array([10, 20, 30])

# Menambahkan vektor ke matriks
# Vektor akan di-broadcast (disalin secara virtual) ke setiap baris matriks
hasil = matriks + vektor
print(hasil)
# Output:
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

[6 7 8]
[[11 22 33]
 [14 25 36]
 [17 28 39]]
